### ISSUE TITLE
Remove banner

### ISSUE THREAD

**Issue by 6temes** [cryptopunksnotdead/faq#1]
Hi,

As in csvreader/csvreader#5, it would be good to remove the banner, so it does not generate noise in the console.

https://github.com/csvreader/csvrecord/blob/92451dbd35e7132178f351e4b3a0596897733797/lib/csvrecord.rb#L15

Thanks!

**Comment by geraldb** [comment]
Good point. Updated the code. Will get (pushed) out with the next gem version. Cheers. Prost.

**Comment by 6temes** [comment]
Thanks! :)

**Comment by geraldb** [comment]
FYI: Pushing gem to https://rubygems.org... Successfully registered gem: csvrecord (0.4.3)
